<!-- Generated by ::xowiki::ADP_Generator on Wed Mar 14 14:38:53 CET 2007 -->
<!-- The following DIV is needed for overlib to function! -->
  <div id="overDiv" style="position:absolute; visibility:hidden; z-index:1000;"></div>	
<div class='xowiki-content'>

@top_portlets;noquote@
@content;noquote@

</div> <!-- class='xowiki-content' -->
